//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThiTraMi_2210900041.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class NTTM_TACGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NTTM_TACGIA()
        {
            this.NTTM_SACH = new HashSet<NTTM_SACH>();
        }
        [DisplayName("Mã tác giả")]           
        public string Nttm_MaTG { get; set; }
        [DisplayName("Tên tác giả")]
        public string Nttm_TenTacGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NTTM_SACH> NTTM_SACH { get; set; }
    }
}
