//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThiTraMi_2210900041.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class NTTM_SACH
    {
        [DisplayName("Mã sách")]
        public string Nttm_MaSach { get; set; }
        [DisplayName("Tên sách")]
        public string Nttm_TenSach { get; set; }
        [DisplayName("Số Trang")]
        public Nullable<int> Nttm_SoTrang { get; set; }
        [DisplayName("Năm Xuất Bản")]
        public Nullable<int> Nttm_NamXB { get; set; }
        [DisplayName("Mã tác giả")]
        public string Nttm_MaTG { get; set; }
        [DisplayName("Trạng thái")]
        public Nullable<bool> Nttm_TrangThai { get; set; }
    
        public virtual NTTM_TACGIA NTTM_TACGIA { get; set; }
    }
}
