//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NttmK22CNT4Lesson11_2210900041.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NttmK22CNT4Lesson11DbEntities : DbContext
    {
        public NttmK22CNT4Lesson11DbEntities()
            : base("name=NttmK22CNT4Lesson11DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NttmCategory> NttmCategories { get; set; }
        public virtual DbSet<NttmProduct> NttmProducts { get; set; }
    }
}
