//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NttmK22CNT4Lesson11_2210900041.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NttmProduct
    {
        public int NttmID2210900041 { get; set; }
        public string NttmProName { get; set; }
        public Nullable<int> NttmQty { get; set; }
        public Nullable<double> NttmPrice { get; set; }
        public Nullable<int> NttmCateId { get; set; }
        public Nullable<bool> NttmActive { get; set; }
    
        public virtual NttmCategory NttmCategory { get; set; }
    }
}
