//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NttmK22CNT4Lesson11_2210900041.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NttmCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NttmCategory()
        {
            this.NttmProducts = new HashSet<NttmProduct>();
        }
        [Display(Name = "Mã danh mục")]
        public int NttmID { get; set; }

        [Display(Name = "Tên danh mục")]
        public string NttmCateName { get; set; }

        [Display(Name = "Trạng thái")]
        public Nullable<bool> NttmStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NttmProduct> NttmProducts { get; set; }
    }
}
