//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NttmLesson07.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nttmSinhVien
    {
        public string NttmMaSV { get; set; }
        public string NttmHoSV { get; set; }
        public string NttmTenSV { get; set; }
        public Nullable<bool> NttmPhai { get; set; }
        public string NttmEmail { get; set; }
        public string NttmPhone { get; set; }
        public string NttmMaKH { get; set; }
        public Nullable<bool> NttmTrangThai { get; set; }
    
        public virtual nttmKhoa nttmKhoa { get; set; }
    }
}
