//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NttmK22CNT4Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NttmAccount
    {
        public int NttmID { get; set; }
        public string NttmUserName { get; set; }
        public string NttmPassWord { get; set; }
        public string NttmFullName { get; set; }
        public string NttmEmail { get; set; }
        public string NttmPhone { get; set; }
        public Nullable<bool> NttmActive { get; set; }
    }
}
