//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NttmLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NttmSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NttmSinhVien()
        {
            this.NttmKetQuas = new HashSet<NttmKetQua>();
        }
    
        public string NttmMaSV { get; set; }
        public string NttmHoSV { get; set; }
        public string NttmTenSV { get; set; }
        public Nullable<bool> NttmPhai { get; set; }
        public Nullable<System.DateTime> NttmNgaySinh { get; set; }
        public string NttmNoiSinh { get; set; }
        public string NttmMaKH { get; set; }
        public Nullable<decimal> NttmHocBong { get; set; }
        public Nullable<decimal> NttmDiemTrungBinh { get; set; }
    
        public virtual NttmKhoa NttmKhoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NttmKetQua> NttmKetQuas { get; set; }
    }
}
