//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NttmLesson09.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NttmK22CNT4QLSinhVienEntities3 : DbContext
    {
        public NttmK22CNT4QLSinhVienEntities3()
            : base("name=NttmK22CNT4QLSinhVienEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NttmKhoa> NttmKhoas { get; set; }
        public virtual DbSet<NttmMonHoc> NttmMonHocs { get; set; }
        public virtual DbSet<NttmSinhVien> NttmSinhViens { get; set; }
        public virtual DbSet<NttmKetQua> NttmKetQuas { get; set; }
    }
}
